excerpts_enabled:
  default: false
  description:
    en: "Excerpt toggle default state"
topic_list_previews_compatibility:
  default: false
  description:
    en: "Topic List Previews only: when toggling excerpts fix tile sizes"
svg_icons: 
  default: 'align-justify'
  type: 'list'
  list_type: 'compact'