excerpts_enabled:
  default: false
  description:
    en: "Excerpt toggle default state"
excerpts_toggle_cause_mini_scroll_for_topic_list_previews_tiles_resize:
  default: false
  description:
    en: "Don't need if you don't have TLP installed: cause minute up & down scroll move to resize tiles on Topic List Previews when toggling excerpts to fix sizes"
svg_icons: 
  default: 'align-justify'
  type: 'list'
  list_type: 'compact'